# Example 1.3 -- Matrix inverse using NumPy and SymPy

In [1]:
import numpy as np
import sympy as sp

In [2]:
# Define the matrix A
A = np.array([[2, 1, 3],
[0, 1, 4],
[1, 0, 2]], dtype=float)

In [3]:
# --- Numerical verification using NumPy ---
A_inv = np.linalg.inv(A)
I_check = A @ A_inv
print("Numerical inverse (NumPy):")
print(A_inv)
print("\nProduct A * A_inv =")
print(I_check)

Numerical inverse (NumPy):
[[ 0.4 -0.4  0.2]
 [ 0.8  0.2 -1.6]
 [-0.2  0.2  0.4]]

Product A * A_inv =
[[ 1.00000000e+00 -5.55111512e-17 -1.11022302e-16]
 [ 0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]


In [ ]:
# --- Symbolic verification using SymPy ---
A_sym = sp.Matrix([[2, 1, 3],
[0, 1, 4],
[1, 0, 2]])
A_inv_sym = A_sym.inv()
I_sym = A_sym * A_inv_sym
sp.pprint(A_inv_sym)
sp.pprint(I_sym)