# Introduction to Matrix Algebra

## Import packages

In [1]:
import numpy as np
import sympy as sp

### Problem 1.

Letting  

\begin{equation}
\mathbf{K} =
\begin{bmatrix}
  1 & -1 & 0 \\
  -1 & 2 & -1 \\
  0 & -1 & 1
\end{bmatrix},
\quad
\mathbf{B} =
\begin{bmatrix}
  2 & 3 & 4 \\
  0 & 1 & 5
\end{bmatrix},
\quad
\mathbf{d} =
\begin{bmatrix}
  2 \\
  -2 \\
  1
\end{bmatrix}
\end{equation}

perform the following matrix multiplications:

\begin{equation}
\text{(a)}\quad \mathbf{K}\mathbf{d}
\qquad
\text{(b)}\quad \mathbf{B}\mathbf{d}
\end{equation}

\begin{equation}
\text{(c)}\quad \mathbf{B}^T\mathbf{B}
\qquad
\text{(d)}\quad \mathbf{K}\mathbf{B}
\end{equation}

In [2]:
K = np.array([[1,-1,0],[-1,2,-1],[0,-1,1]])

In [3]:
K

array([[ 1, -1,  0],
       [-1,  2, -1],
       [ 0, -1,  1]])

In [4]:
B = np.array([[2,3,4],[0,1,5]])

In [5]:
d = np.array([[2],[-2],[1]])

In [6]:
np.shape(K),np.shape(B),np.shape(d)

((3, 3), (2, 3), (3, 1))

In [7]:
np.dot(K,d)

array([[ 4],
       [-7],
       [ 3]])

In [8]:
np.dot(B,d)

array([[2],
       [3]])

In [9]:
np.dot(B.T,B)

array([[ 4,  6,  8],
       [ 6, 10, 17],
       [ 8, 17, 41]])

In [10]:
np.dot(K,B)

ValueError: shapes (3,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

## Problem 2

Let

\begin{equation}
\mathbf{A} =
\begin{bmatrix}
  1 & 2 & 0 \\
  2 & 4 & 2 \\
  1 & 4 & -1
\end{bmatrix},
\qquad
\mathbf{B} =
\begin{bmatrix}
  1 & -1 \\
  -1 & 3
\end{bmatrix}
\end{equation}

Determine the following:

\begin{equation}
\text{(a)} \quad \det(\mathbf{A})
\qquad
\text{(b)} \quad \det(\mathbf{B})
\end{equation}

\begin{equation}
\text{(c)} \quad \mathbf{A}^{-1}
\qquad
\text{(d)} \quad \mathbf{B}^{-1}
\end{equation}

In [11]:
A = np.array([[1,2,0],[2,4,2],[1,4,-1]])

In [12]:
B = np.array([[1,-1],[-1,3]])

In [13]:
np.linalg.det(A)

-4.0

In [14]:
np.linalg.det(B)

2.0

In [15]:
C=np.linalg.inv(A)

In [16]:
C

array([[ 3.  , -0.5 , -1.  ],
       [-1.  ,  0.25,  0.5 ],
       [-1.  ,  0.5 , -0.  ]])

In [17]:
np.dot(C,A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.linalg.inv(B)

array([[1.5, 0.5],
       [0.5, 0.5]])

## Problem 3

Let
\begin{equation}
\mathbf{A}=\left[%
\begin{array}{rrr}
  x \,\,& 0 \,\,& 3x^3 \\
  3 \,\,& x^2+1 \,\,& x^4 \\
  2x \,\,& 6x^3-x \,\,& 1 \\
\end{array}%
\right]\nonumber
\end{equation}
Evaluate $\int_{-1}^{1}\mathbf{A}\,\mathrm{d} x$.


In [19]:
x = sp.symbols('x')

In [20]:
x

x

In [21]:
A = sp.Matrix([[x,0,3*x**3],[3,x**2+1,x**4],[2*x,6*x**3-x,1]])

In [22]:
A

Matrix([
[  x,          0, 3*x**3],
[  3,   x**2 + 1,   x**4],
[2*x, 6*x**3 - x,      1]])

In [23]:
sp.integrate(A,(x,-1,1))

Matrix([
[0,   0,   0],
[6, 8/3, 2/5],
[0,   0,   2]])